# Generated by Django 2.2.4 on 2019-08-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('connects', models.ManyToManyField(related_name='_users_connects_+', to='users.Users')),
            ],
        ),
    ]
