# Generated by Django 2.2.4 on 2019-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='connects',
            field=models.ManyToManyField(blank=True, related_name='_users_connects_+', to='users.Users'),
        ),
    ]
